### ISSUE TITLE
marko test fail with vite 2.9 alpha

### ISSUE THREAD

**Issue by dominikg** [vitejs/vite-ecosystem-ci#47]
`pnpm test -- marko --release 2.8.6` passes but `pnpm test -- marko`  fails with

```
> @marko/vite@2.0.2 mocha
> NODE_ENV=test mocha 'src/**/__tests__/*.test.ts'



  browser-basic
    ✔ dev (1314ms)
    ✔ build (1097ms)

  isomorphic-basic
    ✔ dev (1134ms)
    1) build


  3 passing (4s)
  1 failing

  1) isomorphic-basic
       build:
     /home/dominikg/develop/vite-ecosystem-ci/workspace/marko/marko/src/__tests__/fixtures/isomorphic-basic/dist/index.js:240
window.addEventListener("message", function(ev) {
^

ReferenceError: window is not defined
      at Module.<anonymous> (src/__tests__/fixtures/isomorphic-basic/dist/index.js:240:1)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Module._compile (node_modules/esbuild-register/dist/node.js:2258:26)
      at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Object.newLoader (node_modules/esbuild-register/dist/node.js:2262:9)
      at Object.extensions..js (node_modules/esbuild-register/dist/node.js:4801:24)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (src/__tests__/fixtures/isomorphic-basic/server.js:4:21)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Module._compile (node_modules/esbuild-register/dist/node.js:2258:26)
      at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Object.newLoader (node_modules/esbuild-register/dist/node.js:2262:9)
      at Object.extensions..js (node_modules/esbuild-register/dist/node.js:4801:24)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
      at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
      at async Promise.all (index 0)
      at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
      at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
      at Context.<anonymous> (src/__tests__/main.test.ts:133:12)
```

vite ref: [b0c0efe009c4234c8915a649dc9b1568d1d8a07f](https://github.com/vitejs/vite/tree/b0c0efe009c4234c8915a649dc9b1568d1d8a07f)

**Comment by dominikg** [comment]
@DylanPiercey  any idea what this might be about?

**Comment by dominikg** [comment]
`pnpm bisect -- marko --good v2.8.6` 
```
24bb3e40c1add050c4c7bac9eac6b2edf7ddc73c is the first bad commit
commit 24bb3e40c1add050c4c7bac9eac6b2edf7ddc73c
Author: patak <matias.capeletto@gmail.com>
Date:   Thu Mar 3 14:03:46 2022 +0100

    feat: non-blocking pre bundling of dependencies (#6758)
```
https://github.com/vitejs/vite/pull/6758

**Comment by DylanPiercey** [comment]
@dominikg unsure why but the error suggests that the resolver on the server has been broken. It is pulling in browser assets (mapped via the `browser` pkg json field) into the server bundle.

**Comment by DylanPiercey** [comment]
@patak-dev does https://github.com/vitejs/vite/pull/6758 cause vite to use the same cached optimized files for server and browser? Something like that would lead to incorrectly resolved files like this.

**Comment by patak-dev** [comment]
That shouldn't have changed. I'll review this tomorrow

**Comment by patak-dev** [comment]
The CI was fixed by https://github.com/vitejs/vite/pull/7214, but also see https://github.com/vitejs/vite/pull/7218 as this CI issue uncovered another Vite bug and a Marko bug
